[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Use the official Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Pin Node for the build image (env vars like CONTENTFUL_* should be set in Netlify UI)
[build.environment]
  NODE_VERSION = "20"
